# network
bind 0.0.0.0
port 6379

# logging
daemonize no
loglevel notice
logfile ""

# security
protected-mode yes

#rdb
#save every hour if at least 1 change
save 3600 1
#save every 5 min if 100 change
save 300 100
#save every min if 10000 change

#aof
appendonly yes
appendfsync everysec

#memo manag
maxmemory 100mb
maxmemory-policy allkeys-lru

# turn off default user
user default off

# superuser
user superuser on >admin ~* &* +@all
# events
user events on >events123 ~events:* &* +@all
# comunities
user comunities on >comunities123 ~comunities:* &* +@all