INSERT INTO users (
    full_name,
    email,
    password,
    bio,
    location,
    profile,
    job
) VALUES (
    'fatawa imam al muftin',
    'm@mail.com',
    '$argon2id$v=19$m=65536, t=2, p=2$DwuHLfW8Phd+sfa5OfOoYQ$2y5td8W+dOdEZqPur+qXVbMgRHjN4LmENuI/m8CBy5E',
    'Pengguna EventHub nomor 1, aktif mengikuti event dan komunitas teknologi.',
    'Jakarta',
    '/uploads/profiles/user-01.jpg',
    'Fullstack Developer'
);
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Andi Saputra', 'user02@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$HHEMIXgPAE/Din8IGfU4pQ$WwFFeQqGan3Zq2fj0IP0jiHQuX62waOTrlfRo9uE8mA', 'Pengguna EventHub nomor 2, aktif mengikuti event dan komunitas teknologi.', 'Depok', '/uploads/profiles/user-02.jpg', 'Backend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Budi Nugraha', 'user03@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$rS58qyBQCWWzb9bMhdp75w$ZBYg78PLiR6czs3iSOfzfdxlCXaBDNlRgPK2cpmfpW0', 'Pengguna EventHub nomor 3, aktif mengikuti event dan komunitas teknologi.', 'Tangerang', '/uploads/profiles/user-03.jpg', 'Frontend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Citra Pratama', 'user04@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$th2XYLZjPd47d2RZYFLkeQ$sL96ZOQ1T9SlUWEMB8neCcQbTnDlVLmByKI0KP/Mhkg', 'Pengguna EventHub nomor 4, aktif mengikuti event dan komunitas teknologi.', 'Bandung', '/uploads/profiles/user-04.jpg', 'UI/UX Designer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Dimas Saputra', 'user05@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$lYaoq2cMYcVm6FQYYILYMA$MKlfiPa6Ie4RNAPsx7V3+lRX2BZcZfgdXF+KNBO1780', 'Pengguna EventHub nomor 5, aktif mengikuti event dan komunitas teknologi.', 'Batam', '/uploads/profiles/user-05.jpg', 'Data Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Eka Nugraha', 'user06@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$ARXZ1jondtsHz1D7G99C9A$vGs5kk2HSpuv17pZZWulSQl6kEqd6UM0TDFLi7yvYhU', 'Pengguna EventHub nomor 6, aktif mengikuti event dan komunitas teknologi.', 'Bekasi', '/uploads/profiles/user-06.jpg', 'DevOps Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Fajar Pratama', 'user07@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$ig/wfHSI41koSf+DRkC6QQ$K6ipldknaTmSBq8Wd7z9sTt97Zh0h+6OQRoHNn+FRPY', 'Pengguna EventHub nomor 7, aktif mengikuti event dan komunitas teknologi.', 'Bogor', '/uploads/profiles/user-07.jpg', 'Software Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Gilang Saputra', 'user08@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$ad/UdU3aTljkRX+3uZ5lYQ$4RyO360rl9jTu9yUm/jd99M2sqaMHEtRgkvCGVTdda8', 'Pengguna EventHub nomor 8, aktif mengikuti event dan komunitas teknologi.', 'Surabaya', '/uploads/profiles/user-08.jpg', 'Mobile Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Hana Nugraha', 'user09@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$QFApfhQJC3KE+xiXCk+QoA$yBqWFaa3q0d3hfKBHKB1inOE+ItKjcivWfqPTG9y7KQ', 'Pengguna EventHub nomor 9, aktif mengikuti event dan komunitas teknologi.', 'Yogyakarta', '/uploads/profiles/user-09.jpg', 'Product Manager');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Intan Pratama', 'user10@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$TzKvg9Vmzldur7kxpR4IPw$0+Q5q8BfSKXRaSMRqST2VZ/CZ/fGm/znX/fq6mxN+j8', 'Pengguna EventHub nomor 10, aktif mengikuti event dan komunitas teknologi.', 'Medan', '/uploads/profiles/user-10.jpg', 'QA Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Joko Saputra', 'user11@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$jmiB9YVFBNwpA3s32UQ90A$TiylrxmBLpDaDqHiUaino0c4zu3PNZ0GjijXQjBQ9VU', 'Pengguna EventHub nomor 11, aktif mengikuti event dan komunitas teknologi.', 'Jakarta', '/uploads/profiles/user-11.jpg', 'Student');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Karin Nugraha', 'user12@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$bX3hoNQLDSTNuFFYGJ9Ofg$uAkyKXhvzbV0n0hO/prDojJx4wKgXylcXXQwIzAq5Lg', 'Pengguna EventHub nomor 12, aktif mengikuti event dan komunitas teknologi.', 'Depok', '/uploads/profiles/user-12.jpg', 'System Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Lutfi Pratama', 'user13@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$SSDy75jZ++sVTT8hOhnUUg$BTURjRUmEdHnqVt1gikYxi/trANb6DtjzplqcGUGV9Q', 'Pengguna EventHub nomor 13, aktif mengikuti event dan komunitas teknologi.', 'Tangerang', '/uploads/profiles/user-13.jpg', 'Fullstack Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Mira Saputra', 'user14@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$pnvIxQ/kC+FDwtKOnPeM8w$xcMdO9qrN82WNloekQw6CgKFmNnxW79GlEfhmKwcB9s', 'Pengguna EventHub nomor 14, aktif mengikuti event dan komunitas teknologi.', 'Bandung', '/uploads/profiles/user-14.jpg', 'Backend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Nando Nugraha', 'user15@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$cD79s36Va2asRIcsGRKKZw$+EXcBIQV/N8YIjaFvVa7ao0azVojYFRpT5Rr3aBkTrc', 'Pengguna EventHub nomor 15, aktif mengikuti event dan komunitas teknologi.', 'Batam', '/uploads/profiles/user-15.jpg', 'Frontend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Oki Pratama', 'user16@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$HGC42IF2SLaOBbt9ej6W1A$be3Ss4LqYIWorPZuBZ1oG9GoF4QoNUXIcb4SsoFyWWA', 'Pengguna EventHub nomor 16, aktif mengikuti event dan komunitas teknologi.', 'Bekasi', '/uploads/profiles/user-16.jpg', 'UI/UX Designer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Putri Saputra', 'user17@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$YEAcY2/WKB+dobqnSPzhJA$E1MY+IYYPfUYEgpMQ0Z+HEwGLdVya0aeg67dw5tMoGE', 'Pengguna EventHub nomor 17, aktif mengikuti event dan komunitas teknologi.', 'Bogor', '/uploads/profiles/user-17.jpg', 'Data Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Qori Nugraha', 'user18@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$luJdJG5c00ycGY6vbjI8wQ$E5OvkCucLkcMpqtkp0/UOX8m21qfGiTa5Xb6w4Vmakk', 'Pengguna EventHub nomor 18, aktif mengikuti event dan komunitas teknologi.', 'Surabaya', '/uploads/profiles/user-18.jpg', 'DevOps Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Raka Pratama', 'user19@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$J1GjshMCGaG+uN3F1LmGyQ$6ovXtA3kV3bVbS1IYSVwh9JNKhqK1xAblxWUteTkjNQ', 'Pengguna EventHub nomor 19, aktif mengikuti event dan komunitas teknologi.', 'Yogyakarta', '/uploads/profiles/user-19.jpg', 'Software Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Sari Saputra', 'user20@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$aeaN5AN3npjwoPt4z6g3Gg$8GS72uQ4rOTwkdCfXOcwqWBViLBsL2ip5P2PSEZH/I8', 'Pengguna EventHub nomor 20, aktif mengikuti event dan komunitas teknologi.', 'Medan', '/uploads/profiles/user-20.jpg', 'Mobile Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Taufik Nugraha', 'user21@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$IvCoDNp0q7Shr56HEy3RIw$DEMxC5Xi2F/1bUKa9Y7pgSRYS8LgCAHddzxBCjefdDg', 'Pengguna EventHub nomor 21, aktif mengikuti event dan komunitas teknologi.', 'Jakarta', '/uploads/profiles/user-21.jpg', 'Product Manager');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Ulfa Pratama', 'user22@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$Xx4x+kasqhkGY7+bCnrRmw$Pz9hRD8pZSooZKZ9nq8CjZQ7jnZsfqQbPT47tJBqc+o', 'Pengguna EventHub nomor 22, aktif mengikuti event dan komunitas teknologi.', 'Depok', '/uploads/profiles/user-22.jpg', 'QA Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Vino Saputra', 'user23@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$klStMrzk+7rQ3nR89zieEg$mEzxStIHF0vbs1J2O5BNVlG6jQFXHomSsLAIbCbg0+M', 'Pengguna EventHub nomor 23, aktif mengikuti event dan komunitas teknologi.', 'Tangerang', '/uploads/profiles/user-23.jpg', 'Student');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Wahyu Nugraha', 'user24@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$by21BMgO0CFqthu3SOFttA$s2amdkfnuE6/3B8srefuR6/QgF89XMI7AlK60CO/82c', 'Pengguna EventHub nomor 24, aktif mengikuti event dan komunitas teknologi.', 'Bandung', '/uploads/profiles/user-24.jpg', 'System Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Yuni Pratama', 'user25@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$xarzVYBWKYMzk+iYqju8Bg$LMbsME0e5hqPuYvGnO/F/8R7pDlpudm6Ml748L2dOPg', 'Pengguna EventHub nomor 25, aktif mengikuti event dan komunitas teknologi.', 'Batam', '/uploads/profiles/user-25.jpg', 'Fullstack Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Zaki Saputra', 'user26@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$rv9XkksaBVIagYii+ATARA$frG62arTFT+y8BGY6aI8tCpBBLwc9fXQJdoRNHL5+Qg', 'Pengguna EventHub nomor 26, aktif mengikuti event dan komunitas teknologi.', 'Bekasi', '/uploads/profiles/user-26.jpg', 'Backend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Alya Nugraha', 'user27@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$mP10GEs604zeZhJFT+CTtw$RRcpKO4tQWTWilyU/ch/XGf4Lt2FP9/eXM9spLUzbs8', 'Pengguna EventHub nomor 27, aktif mengikuti event dan komunitas teknologi.', 'Bogor', '/uploads/profiles/user-27.jpg', 'Frontend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Bagas Pratama', 'user28@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$wtMRa1YhTNeKYUGhoClfYw$9LotSJcLGnnmokVVnDQVQUInwFkihfsH+kJAjX2jgnQ', 'Pengguna EventHub nomor 28, aktif mengikuti event dan komunitas teknologi.', 'Surabaya', '/uploads/profiles/user-28.jpg', 'UI/UX Designer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Clara Saputra', 'user29@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$rgO6cu0wznY54O+qw/HYBg$ydL9muX3gTQS2pZmv9KUdGy+u4DL/Xq/KtjZW6hme20', 'Pengguna EventHub nomor 29, aktif mengikuti event dan komunitas teknologi.', 'Yogyakarta', '/uploads/profiles/user-29.jpg', 'Data Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Daffa Nugraha', 'user30@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$Js8dvbDPef1rFlgT6gnFGw$BFMsfvnzk7VCxxjm3A4Yf4PY9F29AGD3xUZqzKMPl2s', 'Pengguna EventHub nomor 30, aktif mengikuti event dan komunitas teknologi.', 'Medan', '/uploads/profiles/user-30.jpg', 'DevOps Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Elsa Pratama', 'user31@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$prjEE9pjM6TLLn+KNQug2g$E3jrh9/BEoZPDlqAnEtRR+6GMkRs2ecPzpUY5fWFxaA', 'Pengguna EventHub nomor 31, aktif mengikuti event dan komunitas teknologi.', 'Jakarta', '/uploads/profiles/user-31.jpg', 'Software Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Farhan Saputra', 'user32@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$uBuSz6awA9h7/uqqh19Nlw$C3XjuR4a1LabhwMCrYW4+xOZzn+q3TECLIL3dgttJYw', 'Pengguna EventHub nomor 32, aktif mengikuti event dan komunitas teknologi.', 'Depok', '/uploads/profiles/user-32.jpg', 'Mobile Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Gita Nugraha', 'user33@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$wgTNemKIlURIQEGjHqr9ug$cwwW2vkmDjunbfRnmd8oizXzJSNMZs6+C8hT/cn7iZI', 'Pengguna EventHub nomor 33, aktif mengikuti event dan komunitas teknologi.', 'Tangerang', '/uploads/profiles/user-33.jpg', 'Product Manager');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Hendra Pratama', 'user34@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$96r2R18x8bbqDURev546AQ$Znet0sXsINbuBDZJQ0H51761b6SQyUtjtaPNGcr/3d8', 'Pengguna EventHub nomor 34, aktif mengikuti event dan komunitas teknologi.', 'Bandung', '/uploads/profiles/user-34.jpg', 'QA Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Indra Saputra', 'user35@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$JbLsH1E7o8PCIYg8qNrcNg$cbzGR5zMrTwoauUnE9N+ZZGHL1DxjZxJ2KQ9GyQ5E7o', 'Pengguna EventHub nomor 35, aktif mengikuti event dan komunitas teknologi.', 'Batam', '/uploads/profiles/user-35.jpg', 'Student');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Jihan Nugraha', 'user36@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$aW17YEBvgFljFPh1RrgdvQ$ASTLmsY+YdLP9lK4TOHHQW1xNqQK38Vty+pMdrvrr2g', 'Pengguna EventHub nomor 36, aktif mengikuti event dan komunitas teknologi.', 'Bekasi', '/uploads/profiles/user-36.jpg', 'System Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Kevin Pratama', 'user37@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$3QqOKu8FMmndSvpkVAHzLg$oZYAkGGsEOZgrPlUqoT+Y0udgT1DD6K9EXebKCcXx8g', 'Pengguna EventHub nomor 37, aktif mengikuti event dan komunitas teknologi.', 'Bogor', '/uploads/profiles/user-37.jpg', 'Fullstack Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Laras Saputra', 'user38@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$Qczj+KK87oH0H373/zJwtw$dU9EaF+fiuGggfl5W8ZP5bUDkvvJtF3nyXy0ohe4szA', 'Pengguna EventHub nomor 38, aktif mengikuti event dan komunitas teknologi.', 'Surabaya', '/uploads/profiles/user-38.jpg', 'Backend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Maulana Nugraha', 'user39@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$r5/BUvkvtHPKLBeuIqefIg$2vZAZGIjI1hLUoRVz3G2zjK8l1Iu/eI/4FjiUAOh3j4', 'Pengguna EventHub nomor 39, aktif mengikuti event dan komunitas teknologi.', 'Yogyakarta', '/uploads/profiles/user-39.jpg', 'Frontend Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Nadia Pratama', 'user40@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$AD58DfAamq0apa9WVAVSBQ$3suOjdmak/UT6BxNNzUfggTzHTJAb/047fhjdhMhReM', 'Pengguna EventHub nomor 40, aktif mengikuti event dan komunitas teknologi.', 'Medan', '/uploads/profiles/user-40.jpg', 'UI/UX Designer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Oscar Saputra', 'user41@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$3WJxb4txzkRqnVkzTKoKNg$SOGDYHSj7N9YCxbpGVmZLgn8tx/FnSqDGwdcL+VWMuM', 'Pengguna EventHub nomor 41, aktif mengikuti event dan komunitas teknologi.', 'Jakarta', '/uploads/profiles/user-41.jpg', 'Data Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Prita Nugraha', 'user42@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$ykpDdEG7dIe7UtXejITaxQ$h+Nkww4ODzCSiw7DmXIlpzG+v5ZO0OLUATQnd97d7EQ', 'Pengguna EventHub nomor 42, aktif mengikuti event dan komunitas teknologi.', 'Depok', '/uploads/profiles/user-42.jpg', 'DevOps Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Rendi Pratama', 'user43@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$MoMJ/WF2zVRIh34ZfA08jQ$YJteUBtwFxUPkWMkx9Cr0N+cEgXR8cpNfFF6liJtL3E', 'Pengguna EventHub nomor 43, aktif mengikuti event dan komunitas teknologi.', 'Tangerang', '/uploads/profiles/user-43.jpg', 'Software Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Sinta Saputra', 'user44@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$4OBgP37CHJQdnvq705XZ3g$8eYEEELB1I68qJ407PICqboALD6d+BiHYTb+deLdWUs', 'Pengguna EventHub nomor 44, aktif mengikuti event dan komunitas teknologi.', 'Bandung', '/uploads/profiles/user-44.jpg', 'Mobile Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Tegar Nugraha', 'user45@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$ibVu+iC0IZIL5iXHmQwedA$5SvC1qNvwiJK+VEVOHqk4aIXJ+J1z6YYDFc46h+nzoM', 'Pengguna EventHub nomor 45, aktif mengikuti event dan komunitas teknologi.', 'Batam', '/uploads/profiles/user-45.jpg', 'Product Manager');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Umar Pratama', 'user46@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$qNsG/Iw67ztsJ+uIc9NHrw$w+K4dJg6Q/6KaR03uTKYNp3U8+4S8H45BepGIhQO994', 'Pengguna EventHub nomor 46, aktif mengikuti event dan komunitas teknologi.', 'Bekasi', '/uploads/profiles/user-46.jpg', 'QA Engineer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Vania Saputra', 'user47@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$BlQ0aV2dKt5x10pthQ87oA$ECATnFTpXP4TkitiVOY2/bk857fahH/iuC1LT8xhZTY', 'Pengguna EventHub nomor 47, aktif mengikuti event dan komunitas teknologi.', 'Bogor', '/uploads/profiles/user-47.jpg', 'Student');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Wulan Nugraha', 'user48@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$DLz+m9w3pQd9Gr8T6NvByw$OQG9kDGf/Ckxys5juF8jXXPHD/E45z8W4f1begHAeJ4', 'Pengguna EventHub nomor 48, aktif mengikuti event dan komunitas teknologi.', 'Surabaya', '/uploads/profiles/user-48.jpg', 'System Analyst');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Yusuf Pratama', 'user49@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$JuSJFvFrpG7WOiTigQCwrw$EZ1Vlbv7/ZmeqtekJc2Z6CS5B8PFyGRP6/wsvGugqnM', 'Pengguna EventHub nomor 49, aktif mengikuti event dan komunitas teknologi.', 'Yogyakarta', '/uploads/profiles/user-49.jpg', 'Fullstack Developer');
INSERT INTO users (full_name, email, password, bio, location, profile, job) VALUES ('Zahra Saputra', 'user50@eventhub.test', '$argon2id$v=19$m=65536,t=2,p=2$aZNH2klfMYxP3u5NOAwN8g$wuvqD2hFk6Ul7w7/7TVuKBur3K895KgZkxWSvzp+M1g', 'Pengguna EventHub nomor 50, aktif mengikuti event dan komunitas teknologi.', 'Medan', '/uploads/profiles/user-50.jpg', 'Backend Developer');
