INSERT INTO testimonials (text, users_id) VALUES ('Platform ini memudahkan saya menemukan event teknologi yang relevan. (Testimoni #1)', 2);
INSERT INTO testimonials (text, users_id) VALUES ('Informasi event cukup lengkap dan mudah dipahami. (Testimoni #2)', 4);
INSERT INTO testimonials (text, users_id) VALUES ('Saya suka fitur pencarian dan filter event. (Testimoni #3)', 6);
INSERT INTO testimonials (text, users_id) VALUES ('Komunitas yang tersedia membantu saya menemukan networking baru. (Testimoni #4)', 8);
INSERT INTO testimonials (text, users_id) VALUES ('Proses registrasi event terasa sederhana. (Testimoni #5)', 10);
INSERT INTO testimonials (text, users_id) VALUES ('Platform ini memudahkan saya menemukan event teknologi yang relevan. (Testimoni #6)', 12);
INSERT INTO testimonials (text, users_id) VALUES ('Informasi event cukup lengkap dan mudah dipahami. (Testimoni #7)', 14);
INSERT INTO testimonials (text, users_id) VALUES ('Saya suka fitur pencarian dan filter event. (Testimoni #8)', 16);
INSERT INTO testimonials (text, users_id) VALUES ('Komunitas yang tersedia membantu saya menemukan networking baru. (Testimoni #9)', 18);
INSERT INTO testimonials (text, users_id) VALUES ('Proses registrasi event terasa sederhana. (Testimoni #10)', 20);
INSERT INTO testimonials (text, users_id) VALUES ('Platform ini memudahkan saya menemukan event teknologi yang relevan. (Testimoni #11)', 22);
INSERT INTO testimonials (text, users_id) VALUES ('Informasi event cukup lengkap dan mudah dipahami. (Testimoni #12)', 24);
INSERT INTO testimonials (text, users_id) VALUES ('Saya suka fitur pencarian dan filter event. (Testimoni #13)', 26);
INSERT INTO testimonials (text, users_id) VALUES ('Komunitas yang tersedia membantu saya menemukan networking baru. (Testimoni #14)', 28);
INSERT INTO testimonials (text, users_id) VALUES ('Proses registrasi event terasa sederhana. (Testimoni #15)', 30);
INSERT INTO testimonials (text, users_id) VALUES ('Platform ini memudahkan saya menemukan event teknologi yang relevan. (Testimoni #16)', 32);
INSERT INTO testimonials (text, users_id) VALUES ('Informasi event cukup lengkap dan mudah dipahami. (Testimoni #17)', 34);
INSERT INTO testimonials (text, users_id) VALUES ('Saya suka fitur pencarian dan filter event. (Testimoni #18)', 36);
INSERT INTO testimonials (text, users_id) VALUES ('Komunitas yang tersedia membantu saya menemukan networking baru. (Testimoni #19)', 38);
INSERT INTO testimonials (text, users_id) VALUES ('Proses registrasi event terasa sederhana. (Testimoni #20)', 40);
INSERT INTO testimonials (text, users_id) VALUES ('Platform ini memudahkan saya menemukan event teknologi yang relevan. (Testimoni #21)', 42);
INSERT INTO testimonials (text, users_id) VALUES ('Informasi event cukup lengkap dan mudah dipahami. (Testimoni #22)', 44);
INSERT INTO testimonials (text, users_id) VALUES ('Saya suka fitur pencarian dan filter event. (Testimoni #23)', 46);
INSERT INTO testimonials (text, users_id) VALUES ('Komunitas yang tersedia membantu saya menemukan networking baru. (Testimoni #24)', 48);
INSERT INTO testimonials (text, users_id) VALUES ('Proses registrasi event terasa sederhana. (Testimoni #25)', 50);
