INSERT INTO speaker (name, position_job) VALUES ('Arif Pratama', 'Senior Backend Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Nadia Putri', 'Frontend Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Rizky Maulana', 'DevOps Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Salsa Maharani', 'Product Designer');
INSERT INTO speaker (name, position_job) VALUES ('Bima Saputra', 'Data Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Dinda Larasati', 'Software Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Fajar Ramadhan', 'Cyber Security Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Kevin Wijaya', 'Mobile Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Aulia Rahman', 'AI Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Citra Dewi', 'Product Manager');
INSERT INTO speaker (name, position_job) VALUES ('Raka Hidayat', 'Cloud Architect');
INSERT INTO speaker (name, position_job) VALUES ('Maya Sari', 'Technical Writer');
INSERT INTO speaker (name, position_job) VALUES ('Doni Kurniawan', 'Fullstack Developer');
INSERT INTO speaker (name, position_job) VALUES ('Nabila Zahra', 'Product Designer');
INSERT INTO speaker (name, position_job) VALUES ('Ilham Akbar', 'Database Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Putri Anggraini', 'Software Architect');
INSERT INTO speaker (name, position_job) VALUES ('Yoga Prasetyo', 'SRE Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Vina Oktaviani', 'Community Manager');
INSERT INTO speaker (name, position_job) VALUES ('Galih Nugraha', 'QA Engineer');
INSERT INTO speaker (name, position_job) VALUES ('Adit Firmansyah', 'Engineering Manager');
