name: "be-eventhub images"
on:
    push:
        branches: 
            - cicd
jobs:
    hallo:
        runs-on: ubuntu-24.04
        steps:
          - name: say hallo
            run: echo"hallo word"
          - name: whoami
            run: echo"i am ${{github.actor}}"